# Generated by Django 6.0.7 on 2026-08-19 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao', '0001_initial'),
        ('livro_colecao', '0001_initial'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro_Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colecao.colecao')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro')),
            ],
        ),
        migrations.DeleteModel(
            name='Editora',
        ),
    ]
