# Generated by Django 6.0.7 on 2026-08-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='colecoes_filhas',
            field=models.ManyToManyField(blank=True, related_name='colecoes_pais', to='colecao.colecao'),
        ),
    ]
