# Generated by Django 6.0.7 on 2026-08-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField()),
                ('numero_paginas', models.IntegerField()),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
