# Generated by Django 6.0.7 on 2026-08-13 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edicao', '0001_initial'),
        ('editora', '0001_initial'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicao',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editora.editora'),
        ),
        migrations.AddField(
            model_name='edicao',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro'),
        ),
    ]
