# Generated by Django 6.1 on 2026-09-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edicao', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicao',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
    ]
