# Generated by Django 6.1 on 2026-08-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('curtida', models.BooleanField(default=False)),
            ],
        ),
    ]
