# Generated by Django 6.1 on 2026-09-17 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0006_alter_avaliacao_curtida_alter_avaliacao_livro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='curtida',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.TextField(max_length=25),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='curtida',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes_curtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
